version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  redis:
    image: redis
    container_name: cache
    restart: always
    expose:
      - 6379

  server:
    build: .
    container_name: server
    restart: always
    ports:
      - 4000